# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newTeam.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAttribute(QtCore.Qt.WA_StyledBackground, True)
        self.centralwidget.setStyleSheet("""
            background-image:  url("C:/Users/Dell/Desktop/gcs_v1.8/resources/images/AeroCore.png");
            background-repeat: no-repeat;
            background-position: center;
        """)
        self.centralwidget.setObjectName("centralwidget")

        self.arm_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.arm_pushButton.setGeometry(QtCore.QRect(1370, 177, 101, 31))
        self.arm_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.arm_pushButton.setObjectName("arm_pushButton")
        self.disarm_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.disarm_pushButton.setGeometry(QtCore.QRect(1490, 177, 101, 31))
        self.disarm_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"")
        self.disarm_pushButton.setObjectName("disarm_pushButton")
        self.takeOff_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.takeOff_pushButton.setGeometry(QtCore.QRect(1370, 300, 101, 31))
        self.takeOff_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.takeOff_pushButton.setObjectName("takeOff_pushButton")
        self.land_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.land_pushButton.setGeometry(QtCore.QRect(1490, 300, 101, 31))
        self.land_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.land_pushButton.setObjectName("land_pushButton")
        self.changeMode_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.changeMode_pushButton.setGeometry(QtCore.QRect(1690, 232, 121, 31))
        self.changeMode_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.changeMode_pushButton.setObjectName("changeMode_pushButton")
        self.openTelemetry_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.openTelemetry_pushButton.setGeometry(QtCore.QRect(1510, 470, 41, 21))
        self.openTelemetry_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.openTelemetry_pushButton.setObjectName("openTelemetry_pushButton")
        self.closeTelemetry_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeTelemetry_pushButton.setGeometry(QtCore.QRect(1560, 470, 41, 21))
        self.closeTelemetry_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.closeTelemetry_pushButton.setObjectName("closeTelemetry_pushButton")
        self.openCamera_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.openCamera_pushButton.setGeometry(QtCore.QRect(1510, 532, 41, 21))
        self.openCamera_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.openCamera_pushButton.setObjectName("openCamera_pushButton")
        self.closeCamera_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeCamera_pushButton.setGeometry(QtCore.QRect(1560, 532, 41, 21))
        self.closeCamera_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.closeCamera_pushButton.setObjectName("closeCamera_pushButton")
        self.addMarker_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addMarker_pushButton.setGeometry(QtCore.QRect(50, 740, 111, 31))
        self.addMarker_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.addMarker_pushButton.setObjectName("addMarker_pushButton")
        self.clearPath_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearPath_pushButton.setGeometry(QtCore.QRect(50, 790, 111, 31))
        self.clearPath_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.clearPath_pushButton.setObjectName("clearPath_pushButton")
        self.loadMission_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadMission_pushButton.setGeometry(QtCore.QRect(50, 840, 111, 31))
        self.loadMission_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.loadMission_pushButton.setObjectName("loadMission_pushButton")
        self.uploadMission_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadMission_pushButton.setGeometry(QtCore.QRect(50, 890, 111, 31))
        self.uploadMission_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.uploadMission_pushButton.setObjectName("uploadMission_pushButton")
        self.clearMarker_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearMarker_pushButton.setGeometry(QtCore.QRect(180, 740, 111, 31))
        self.clearMarker_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.clearMarker_pushButton.setObjectName("clearMarker_pushButton")
        self.goToFocus_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.goToFocus_pushButton.setGeometry(QtCore.QRect(180, 790, 111, 31))
        self.goToFocus_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.goToFocus_pushButton.setObjectName("goToFocus_pushButton")
        self.saveMission_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveMission_pushButton.setGeometry(QtCore.QRect(180, 840, 111, 31))
        self.saveMission_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.saveMission_pushButton.setObjectName("saveMission_pushButton")
        self.downloadMission_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadMission_pushButton.setGeometry(QtCore.QRect(180, 890, 111, 31))
        self.downloadMission_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.downloadMission_pushButton.setObjectName("downloadMission_pushButton")
        self.snapshoot_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.snapshoot_pushButton.setGeometry(QtCore.QRect(1100, 120, 200, 18))
        self.snapshoot_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.snapshoot_pushButton.setObjectName("snapshoot_pushButton")
        self.exit_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exit_pushButton.setGeometry(QtCore.QRect(1860, 20, 31, 21))
        self.exit_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.minimize_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.minimize_pushButton.setGeometry(QtCore.QRect(1820, 24, 21, 21))
        self.minimize_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.minimize_pushButton.setObjectName("minimize_pushButton")
        self.profile_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.profile_pushButton.setGeometry(QtCore.QRect(1720, 20, 41, 31))
        self.profile_pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* ← metin %100 şeffaf */\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background: none;\n"
"    border: 0;\n"
"    color: rgba(0, 0, 0, 0);      /* hover/press’te de görünmez kalsın */\n"
"}\n"
"\n"
"")
        self.profile_pushButton.setObjectName("profile_pushButton")
        self.alt_missionLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.alt_missionLineEdit.setGeometry(QtCore.QRect(50, 950, 241, 22))
        self.alt_missionLineEdit.setStyleSheet("/* QLineEdit – iç/dış şeffaf, yazı beyaz */\n"
"QLineEdit {\n"
"    background: transparent;   /* << anahtar: tam saydam zemin */\n"
"    border: 0;                 /* kenarlık yok */\n"
"    color: #ffffff;            /* metin beyaz */\n"
"}\n"
"\n"
"QLineEdit:hover,\n"
"QLineEdit:focus {              /* hover veya odak durumunda da aynı kalsın */\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz */\n"
"QLineEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.alt_missionLineEdit.setText("")
        self.alt_missionLineEdit.setObjectName("alt_missionLineEdit")
        self.altitudeLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.altitudeLineEdit.setGeometry(QtCore.QRect(1370, 258, 201, 22))
        self.altitudeLineEdit.setStyleSheet("/* QLineEdit – iç/dış şeffaf, yazı beyaz */\n"
"QLineEdit {\n"
"    background: transparent;   /* << anahtar: tam saydam zemin */\n"
"    border: 0;                 /* kenarlık yok */\n"
"    color: #ffffff;            /* metin beyaz */\n"
"}\n"
"\n"
"QLineEdit:hover,\n"
"QLineEdit:focus {              /* hover veya odak durumunda da aynı kalsın */\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz */\n"
"QLineEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.altitudeLineEdit.setText("")
        self.altitudeLineEdit.setObjectName("altitudeLineEdit")
        self.latitude_textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.latitude_textEdit_2.setGeometry(QtCore.QRect(1152, 810, 191, 20))
        self.latitude_textEdit_2.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.latitude_textEdit_2.setObjectName("latitude_textEdit_2")
        self.currentMode_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.currentMode_textEdit.setGeometry(QtCore.QRect(1152, 868, 191, 20))
        self.currentMode_textEdit.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.currentMode_textEdit.setObjectName("currentMode_textEdit")
        self.yaw_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.yaw_textEdit.setGeometry(QtCore.QRect(1152, 749, 191, 20))
        self.yaw_textEdit.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.yaw_textEdit.setObjectName("yaw_textEdit")
        self.pitch_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.pitch_textEdit.setGeometry(QtCore.QRect(1416, 749, 191, 20))
        self.pitch_textEdit.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.pitch_textEdit.setObjectName("pitch_textEdit")
        self.longitude_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.longitude_textEdit.setGeometry(QtCore.QRect(1416, 810, 191, 20))
        self.longitude_textEdit.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.longitude_textEdit.setObjectName("longitude_textEdit")
        self.roll_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.roll_textEdit.setGeometry(QtCore.QRect(1680, 749, 191, 20))
        self.roll_textEdit.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.roll_textEdit.setObjectName("roll_textEdit")
        self.altitude_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.altitude_textEdit.setGeometry(QtCore.QRect(1680, 810, 191, 20))
        self.altitude_textEdit.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.altitude_textEdit.setObjectName("altitude_textEdit")
        self.speed_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.speed_textEdit.setGeometry(QtCore.QRect(1416, 868, 191, 20))
        self.speed_textEdit.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.speed_textEdit.setObjectName("speed_textEdit")
        self.hdop_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.hdop_textEdit.setGeometry(QtCore.QRect(1680, 868, 191, 20))
        self.hdop_textEdit.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.hdop_textEdit.setObjectName("hdop_textEdit")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(39, 1034, 271, 10))
        self.progressBar.setStyleSheet("color: rgb(85, 255, 255);\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.currentState_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.currentState_textEdit.setGeometry(QtCore.QRect(1110, 980, 251, 61))
        self.currentState_textEdit.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.currentState_textEdit.setObjectName("currentState_textEdit")
        self.currentState_textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.currentState_textEdit_2.setGeometry(QtCore.QRect(1380, 980, 251, 61))
        self.currentState_textEdit_2.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.currentState_textEdit_2.setObjectName("currentState_textEdit_2")
        self.waypoint_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.waypoint_listWidget.setGeometry(QtCore.QRect(1650, 980, 241, 61))
        self.waypoint_listWidget.setStyleSheet("/* Tüm liste ve iç viewport’u şeffaf, metin beyaz */\n"
"QListWidget,\n"
"QListWidget::viewport,\n"
"QListView,\n"
"QListView::viewport {\n"
"    background: transparent;      /* zemin %100 saydam */\n"
"    border: 0;\n"
"    color: #ffffff;               /* metin beyaz */\n"
"}\n"
"\n"
"/* Liste öğeleri */\n"
"QListWidget::item,\n"
"QListView::item {\n"
"    background: transparent;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili / hover durumları için yarı saydam vurgu */\n"
"QListWidget::item:selected,\n"
"QListView::item:selected {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"QListWidget::item:hover,\n"
"QListView::item:hover {\n"
"    background: rgba(255,255,255,20);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Kaydırma çubuğu da şeffaf kalsın (isteğe bağlı) */\n"
"QListWidget QScrollBar:vertical,\n"
"QListWidget QScrollBar:horizontal,\n"
"QListView  QScrollBar:vertical,\n"
"QListView  QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.waypoint_listWidget.setObjectName("waypoint_listWidget")
        self.criticalShown_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.criticalShown_textEdit.setGeometry(QtCore.QRect(1630, 430, 261, 81))
        self.criticalShown_textEdit.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.criticalShown_textEdit.setObjectName("criticalShown_textEdit")
        self.mobileBox_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.mobileBox_textEdit.setGeometry(QtCore.QRect(1630, 570, 261, 71))
        self.mobileBox_textEdit.setStyleSheet("/* QTextEdit – iç/dış şeffaf, yazı beyaz */\n"
"QTextEdit {\n"
"    background: transparent;    /* zemin %100 saydam */\n"
"    border: 0;                  /* kenarlık yok */\n"
"    color: #ffffff;             /* metin beyaz */\n"
"}\n"
"\n"
"/* Odak veya hover’da da zemin değişmesin */\n"
"QTextEdit:hover,\n"
"QTextEdit:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Seçili metnin arka planı yarı saydam beyaz olsun */\n"
"QTextEdit::selection {\n"
"    background: rgba(255,255,255,40);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* (İsteğe bağlı) Scrollbar varsa görünümünü koru – zemin saydam kalır */\n"
"QTextEdit QScrollBar:vertical,\n"
"QTextEdit QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: 0;\n"
"}\n"
"")
        self.mobileBox_textEdit.setObjectName("mobileBox_textEdit")
        self.comPortTelemetry_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comPortTelemetry_comboBox.setGeometry(QtCore.QRect(1370, 469, 131, 22))
        self.comPortTelemetry_comboBox.setStyleSheet("/* ---------- Kapalı durum (görünür ComboBox) ---------- */\n"
"QComboBox {\n"
"    background: transparent;      /* kutu saydam                      */\n"
"    border: 0;                    /* çerçeve yok                      */\n"
"    color: #ffffff;               /* kapalıyken metin beyaz olsun     */\n"
"    padding-right: 18px;          /* aşağı ok için iç boşluk          */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Hover / focus’ta da zemin değişmesin */\n"
"QComboBox:hover,\n"
"QComboBox:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* ---------- Açılan liste (popup) ---------- */\n"
"QComboBox QAbstractItemView,\n"
"QComboBox QListView,\n"
"QComboBox QListView::viewport {\n"
"    background: #ffffff;          /* liste zemini beyaz               */\n"
"    border: 0;\n"
"    color: #000000;               /* öğe metni siyah                  */\n"
"}\n"
"\n"
"/* Liste öğeleri */\n"
"QComboBox QAbstractItemView::item {\n"
"    background: #ffffff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* Seçili / hover öğe – hafif gri vurgulu */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background: #d0d0d0;          /* beyaz üzerinde gri vurgu         */\n"
"    color: #000000;\n"
"}\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background: #e8e8e8;\n"
"    color: #000000;\n"
"}\n"
"")
        self.comPortTelemetry_comboBox.setObjectName("comPortTelemetry_comboBox")
        self.videoCapture_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.videoCapture_comboBox.setGeometry(QtCore.QRect(1370, 534, 131, 22))
        self.videoCapture_comboBox.setStyleSheet("/* ---------- Kapalı durum (görünür ComboBox) ---------- */\n"
"QComboBox {\n"
"    background: transparent;      /* kutu saydam                      */\n"
"    border: 0;                    /* çerçeve yok                      */\n"
"    color: #ffffff;               /* kapalıyken metin beyaz olsun     */\n"
"    padding-right: 18px;          /* aşağı ok için iç boşluk          */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Hover / focus’ta da zemin değişmesin */\n"
"QComboBox:hover,\n"
"QComboBox:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* ---------- Açılan liste (popup) ---------- */\n"
"QComboBox QAbstractItemView,\n"
"QComboBox QListView,\n"
"QComboBox QListView::viewport {\n"
"    background: #ffffff;          /* liste zemini beyaz               */\n"
"    border: 0;\n"
"    color: #000000;               /* öğe metni siyah                  */\n"
"}\n"
"\n"
"/* Liste öğeleri */\n"
"QComboBox QAbstractItemView::item {\n"
"    background: #ffffff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* Seçili / hover öğe – hafif gri vurgulu */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background: #d0d0d0;          /* beyaz üzerinde gri vurgu         */\n"
"    color: #000000;\n"
"}\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background: #e8e8e8;\n"
"    color: #000000;\n"
"}\n"
"")
        self.videoCapture_comboBox.setObjectName("videoCapture_comboBox")
        self.resolution_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.resolution_comboBox.setGeometry(QtCore.QRect(1370, 602, 131, 22))
        self.resolution_comboBox.setStyleSheet("/* ---------- Kapalı durum (görünür ComboBox) ---------- */\n"
"QComboBox {\n"
"    background: transparent;      /* kutu saydam                      */\n"
"    border: 0;                    /* çerçeve yok                      */\n"
"    color: #ffffff;               /* kapalıyken metin beyaz olsun     */\n"
"    padding-right: 18px;          /* aşağı ok için iç boşluk          */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Hover / focus’ta da zemin değişmesin */\n"
"QComboBox:hover,\n"
"QComboBox:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* ---------- Açılan liste (popup) ---------- */\n"
"QComboBox QAbstractItemView,\n"
"QComboBox QListView,\n"
"QComboBox QListView::viewport {\n"
"    background: #ffffff;          /* liste zemini beyaz               */\n"
"    border: 0;\n"
"    color: #000000;               /* öğe metni siyah                  */\n"
"}\n"
"\n"
"/* Liste öğeleri */\n"
"QComboBox QAbstractItemView::item {\n"
"    background: #ffffff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* Seçili / hover öğe – hafif gri vurgulu */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background: #d0d0d0;          /* beyaz üzerinde gri vurgu         */\n"
"    color: #000000;\n"
"}\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background: #e8e8e8;\n"
"    color: #000000;\n"
"}\n"
"")
        self.resolution_comboBox.setObjectName("resolution_comboBox")
        self.mode_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.mode_comboBox.setGeometry(QtCore.QRect(1652, 193, 190, 22))
        self.mode_comboBox.setStyleSheet("/* ---------- Kapalı durum (görünür ComboBox) ---------- */\n"
"QComboBox {\n"
"    background: transparent;      /* kutu saydam                      */\n"
"    border: 0;                    /* çerçeve yok                      */\n"
"    color: #ffffff;               /* kapalıyken metin beyaz olsun     */\n"
"    padding-right: 18px;          /* aşağı ok için iç boşluk          */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Hover / focus’ta da zemin değişmesin */\n"
"QComboBox:hover,\n"
"QComboBox:focus {\n"
"    background: transparent;\n"
"    border: 0;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* ---------- Açılan liste (popup) ---------- */\n"
"QComboBox QAbstractItemView,\n"
"QComboBox QListView,\n"
"QComboBox QListView::viewport {\n"
"    background: #ffffff;          /* liste zemini beyaz               */\n"
"    border: 0;\n"
"    color: #000000;               /* öğe metni siyah                  */\n"
"}\n"
"\n"
"/* Liste öğeleri */\n"
"QComboBox QAbstractItemView::item {\n"
"    background: #ffffff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* Seçili / hover öğe – hafif gri vurgulu */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background: #d0d0d0;          /* beyaz üzerinde gri vurgu         */\n"
"    color: #000000;\n"
"}\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background: #e8e8e8;\n"
"    color: #000000;\n"
"}\n"
"")
        self.mode_comboBox.setObjectName("mode_comboBox")
        self.bodyDetectedShown_label = QtWidgets.QLabel(self.centralwidget)
        self.bodyDetectedShown_label.setGeometry(QtCore.QRect(60, 140, 141, 131))
        self.bodyDetectedShown_label.setStyleSheet("QLabel {\n"
"    background: transparent;   /* veya background-color: rgba(0,0,0,0); */\n"
"}\n"
"")
        self.bodyDetectedShown_label.setText("")
        self.bodyDetectedShown_label.setObjectName("bodyDetectedShown_label")
        self.woundDetectedShown_label = QtWidgets.QLabel(self.centralwidget)
        self.woundDetectedShown_label.setGeometry(QtCore.QRect(60, 310, 141, 131))
        self.woundDetectedShown_label.setStyleSheet("QLabel {\n"
"    background: transparent;   /* veya background-color: rgba(0,0,0,0); */\n"
"}\n"
"")
        self.woundDetectedShown_label.setText("")
        self.woundDetectedShown_label.setObjectName("woundDetectedShown_label")
        self.fireDetectedShown_label = QtWidgets.QLabel(self.centralwidget)
        self.fireDetectedShown_label.setGeometry(QtCore.QRect(60, 480, 141, 131))
        self.fireDetectedShown_label.setStyleSheet("QLabel {\n"
"    background: transparent;   /* veya background-color: rgba(0,0,0,0); */\n"
"}\n"
"")
        self.fireDetectedShown_label.setText("")
        self.fireDetectedShown_label.setObjectName("fireDetectedShown_label")
        self.cameraShown_label = QtWidgets.QLabel(self.centralwidget)
        self.cameraShown_label.setGeometry(QtCore.QRect(280, 150, 1021, 471))
        self.cameraShown_label.setStyleSheet("QLabel {\n"
"    background: transparent;   /* veya background-color: rgba(0,0,0,0); */\n"
"}\n"
"")
        self.cameraShown_label.setText("")
        self.cameraShown_label.setObjectName("cameraShown_label")
        self.mapShown_label = QtWidgets.QLabel(self.centralwidget)
        self.mapShown_label.setGeometry(QtCore.QRect(350, 690, 721, 341))
        self.mapShown_label.setStyleSheet("QLabel {\n"
"    background: transparent;   /* veya background-color: rgba(0,0,0,0); */\n"
"}\n"
"")
        self.mapShown_label.setText("")
        self.mapShown_label.setObjectName("mapShown_label")
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(1590, 30, 111, 16))
        self.time_label.setStyleSheet("QLabel {\n"
"    background: transparent;   /* veya background-color: rgba(0,0,0,0); */\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.time_label.setObjectName("time_label")
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setGeometry(QtCore.QRect(1450, 30, 111, 16))
        self.date_label.setStyleSheet("QLabel {\n"
"    background: transparent;   /* veya background-color: rgba(0,0,0,0); */\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.date_label.setObjectName("date_label")
        self.weather_label = QtWidgets.QLabel(self.centralwidget)
        self.weather_label.setGeometry(QtCore.QRect(1310, 30, 111, 16))
        self.weather_label.setStyleSheet("QLabel {\n"
"    background: transparent;   /* veya background-color: rgba(0,0,0,0); */\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.weather_label.setObjectName("weather_label")
        self.red_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.red_pushButton.setGeometry(QtCore.QRect(290, 130, 12, 12))
        self.red_pushButton.setStyleSheet("/* ————— NORMAL (bekleme) ————— */\n"
"QPushButton {\n"
"    /* Bordo-siyah degrade zemin  */\n"
"    background: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0  #660000,        /* koyu bordo */\n"
"        stop:1  #000000         /* siyah      */\n"
"    );\n"
"    border: 2px solid #4d0000;   /* koyu bordo kenar */\n"
"    border-radius: 89px;         /* yuvarlak köşe    */\n"
"\n"
"    color: #ffffff;              /* yazı beyaz        */\n"
"    padding: 6px 18px;\n"
"}\n"
"\n"
"/* ————— HOVER —————\n"
"   Hiçbir değişiklik istenmediği için bu bloğu eklemiyoruz.\n"
"*/\n"
"\n"
"/* ————— PRESSED (tıklandı) ————— */\n"
"QPushButton:pressed {\n"
"    background-color: #ff0000;        /* canlı kırmızı dolgu  */\n"
"    border: 2px solid #ff0000;        /* kenar da kırmızı     */\n"
"    border-radius: 10px;\n"
"    color: #ffffff;\n"
"\n"
"    /* Qt 5.12+ ve Qt 6’da \'box-shadow\' destekleniyorsa\n"
"       gerçek dış-parlaklık efekti:                    */\n"
"    box-shadow: 0 0 8px 3px rgba(255,0,0,0.8);\n"
"}\n"
"\n"
"/* Tercihe bağlı: klavye odağındaki mavi çerçeveyi kapatmak */\n"
"QPushButton:focus { outline: none; }\n"
"")
        self.red_pushButton.setText("")
        self.red_pushButton.setIconSize(QtCore.QSize(10, 10))
        self.red_pushButton.setObjectName("red_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.arm_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.disarm_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.takeOff_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.land_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.changeMode_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.openTelemetry_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.closeTelemetry_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.openCamera_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.closeCamera_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.addMarker_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.clearPath_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.loadMission_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.uploadMission_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.clearMarker_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.goToFocus_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.saveMission_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.downloadMission_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.snapshoot_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.exit_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.minimize_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.profile_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.currentState_textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.criticalShown_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.mobileBox_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.time_label.setText(_translate("MainWindow", "zaman"))
        self.date_label.setText(_translate("MainWindow", "tarih"))
        self.weather_label.setText(_translate("MainWindow", "hava"))



