# core/ports/logger_port.py

from typing import Protocol, runtime_checkable

@runtime_checkable
class ILoggerPort(Protocol):
    def debug(self, message: str) -> None: ...
    def info(self,  message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...

