# core/ports/pymavlink_port.py

from typing import Protocol, runtime_checkable, Any

@runtime_checkable
class IPyMavlinkPort(Protocol):
    connected: Any;
    failed: Any;
    disconnected: Any
    telemetry: Any;
    command_ack: Any

    # Bağlantı
    def open_serial(self, port: str, baudrate: int) -> None: ...
    def open_tcp(self, host: str, tcp_port: int) -> None: ...
    def close(self) -> None: ...

    # ----------- yeni üst-seviye komutlar -----------
    def arm(self) -> None: ...
    def disarm(self) -> None: ...
    def land(self) -> None: ...
    def takeoff(self, altitude_m: float) -> None: ...
    def set_mode(self, mode: str) -> None: ...
